### ISSUE TITLE
Change web wallet and discord bot env contract address

### ISSUE THREAD

**Issue by marc-aurele-besner** [subspace/faucet#30]
## Change web wallet and discord bot env contract address

As we deployed a new Faucet contract, we would like to change the contract address in the environment variables to point to this new Contract.

The new Faucet contract is `0xAe7b1b1e458D8EbC8e656A2B87fcbE989831e692`

```[tasklist]
### Tasks
- [x] Change contract address in Netlify
- [x] Change contract address in GitHub secrets and/or AWS env
- [x] Test the Web app
- [x] Test the discord faucet
```

Thank you
